repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: hlint
        name: hlint
        language: system
        files: '\.hs$'
        entry: linting/run.sh hlint
      - id: fourmolu
        name: fourmolu
        language: system
        files: '\.hs$'
        entry: linting/run.sh fourmolu -e -i
