name: http-api-data-qq
version: 0.1.0.1
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
synopsis: Quasiquoter for building URLs with ToHttpApiData types
description: |
  Quasiquoter for building URLs with strings interpolated
  using ToHttpApiData instances
category: Web
license: BSD3
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall -Wcompat
when:
  - condition: impl(ghc >= 8.10)
    ghc-options: -Wunused-packages

github: brandonchinn178/http-api-data-qq

library:
  source-dirs: src
  dependencies:
    - base >= 4.12 && < 5
    - http-api-data
    - template-haskell
    - text

tests:
  http-api-data-qq-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - http-api-data
      - http-api-data-qq
      - http-client
      - tasty
      - tasty-hunit >= 0.10
      - tasty-quickcheck >= 0.8.1
      - text
