name: http-api-data-qq
version: 0.1.0.0
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
synopsis: Quasiquoter for building URLs with ToHttpApiData types
description: |
  Quasiquoter for building URLs with strings interpolated
  using ToHttpApiData instances
category: Web
license: BSD3
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

github: brandonchinn178/http-api-data-qq

library:
  source-dirs: src
  dependencies:
    - base >= 4.12 && < 4.17
    - http-api-data >= 0.4.1.1 && < 0.6
    - template-haskell >= 2.14 && < 2.19
    - text >= 1.2.3.1 && < 1.3

tests:
  http-api-data-qq-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - http-api-data
      - http-api-data-qq
      - http-client
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - text
